/**:
  ros__parameters:
    mujoco_plugins:
      base_velocity_plugin:
        type: "mujoco_ros2_control_plugins/BaseVelocityPlugin"
        body: base_link
        cmd_vel_topic: /cmd_vel
        max_linear_velocity: 1.5
        max_yaw_rate: 2.0
        cmd_timeout: 0.5
