// Copyright 2026 Bilal Gill
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef DIFF_DRIVE_POSITION_CONTROLLER__DIFF_DRIVE_POSITION_CONTROLLER_HPP_
#define DIFF_DRIVE_POSITION_CONTROLLER__DIFF_DRIVE_POSITION_CONTROLLER_HPP_

#include <array>
#include <memory>
#include <vector>

#include "controller_interface/chainable_controller_interface.hpp"
#include "diff_drive_position_controller/odometry.hpp"
#include "nav_msgs/msg/odometry.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_publisher.hpp"
#include "tf2_msgs/msg/tf_message.hpp"

// auto-generated by generate_parameter_library
#include "diff_drive_position_controller/diff_drive_position_controller_parameters.hpp"

namespace diff_drive_position_controller
{

struct Pose2d
{
  double x;
  double y;
  double yaw;
};

struct UnicycleCommand
{
  double linear;
  double angular;
};

struct WheelVelocities
{
  double left;
  double right;
};

struct TrackingGains
{
  double kx;
  double ky;
  double ktheta;
};

/// Wraps an angle to (-pi, pi].
[[nodiscard]] double wrapAngle(double angle);

/// Pose error of `reference` relative to `current`, expressed in the current body frame.
/// The `yaw` field is the wrapped heading error.
[[nodiscard]] Pose2d computeBodyFrameError(const Pose2d & current, const Pose2d & reference);

/// Kanayama nonlinear trajectory-tracking law: body-frame pose error plus
/// reference-velocity feedforward to a unicycle (v, omega) command.
[[nodiscard]] UnicycleCommand trackingControl(
  const Pose2d & error_body, const UnicycleCommand & feedforward, const TrackingGains & gains);

/// Diff-drive inverse kinematics: unicycle command to wheel angular velocities [rad/s].
[[nodiscard]] WheelVelocities inverseKinematics(
  const UnicycleCommand & command, double wheel_separation, double wheel_radius);

/// Chainable controller exporting planar base joint POSITION reference interfaces
/// (`<controller>/<reference_joint_names[i]>/position`) so a JointTrajectoryController
/// can command the base, plus matching position/velocity state interfaces fed from
/// wheel-encoder odometry. Closes the pose loop internally and writes wheel velocity
/// commands. No cmd_vel subscriber: when unchained or references are NaN, the wheels
/// are commanded to zero.
/// @warning Not thread-safe; runs in the controller_manager update loop only.
class DiffDrivePositionController : public controller_interface::ChainableControllerInterface
{
public:
  DiffDrivePositionController() = default;

  [[nodiscard]] controller_interface::InterfaceConfiguration command_interface_configuration()
    const override;

  [[nodiscard]] controller_interface::InterfaceConfiguration state_interface_configuration()
    const override;

  controller_interface::return_type update_reference_from_subscribers(
    const rclcpp::Time & time, const rclcpp::Duration & period) override;

  controller_interface::return_type update_and_write_commands(
    const rclcpp::Time & time, const rclcpp::Duration & period) override;

  controller_interface::CallbackReturn on_init() override;

  controller_interface::CallbackReturn on_configure(
    const rclcpp_lifecycle::State & previous_state) override;

  controller_interface::CallbackReturn on_activate(
    const rclcpp_lifecycle::State & previous_state) override;

  controller_interface::CallbackReturn on_deactivate(
    const rclcpp_lifecycle::State & previous_state) override;

protected:
  std::vector<hardware_interface::CommandInterface::SharedPtr>
  on_export_reference_interfaces_list() override;

  std::vector<hardware_interface::StateInterface::SharedPtr>
  on_export_state_interfaces_list() override;

private:
  void haltWheels();
  void publishOdometry(const rclcpp::Time & time);
  void updateExportedStates();

  std::shared_ptr<ParamListener> param_listener_;
  Params params_;

  Odometry odometry_;

  // Exported interfaces (also stored by the base class; kept here for direct access).
  std::vector<hardware_interface::CommandInterface::SharedPtr> exported_references_;
  std::vector<hardware_interface::StateInterface::SharedPtr> exported_states_;

  // Feedforward state: previous references and filtered (v, omega) feedforward.
  bool prev_reference_valid_ = false;
  Pose2d prev_reference_{0.0, 0.0, 0.0};
  UnicycleCommand filtered_feedforward_{0.0, 0.0};

  std::shared_ptr<rclcpp::Publisher<nav_msgs::msg::Odometry>> odometry_publisher_;
  std::shared_ptr<realtime_tools::RealtimePublisher<nav_msgs::msg::Odometry>>
    realtime_odometry_publisher_;
  std::shared_ptr<rclcpp::Publisher<tf2_msgs::msg::TFMessage>> odometry_transform_publisher_;
  std::shared_ptr<realtime_tools::RealtimePublisher<tf2_msgs::msg::TFMessage>>
    realtime_odometry_transform_publisher_;

  rclcpp::Duration publish_period_ = rclcpp::Duration::from_nanoseconds(0);
  rclcpp::Time previous_publish_timestamp_{0, 0, RCL_CLOCK_UNINITIALIZED};
};

}  // namespace diff_drive_position_controller

#endif  // DIFF_DRIVE_POSITION_CONTROLLER__DIFF_DRIVE_POSITION_CONTROLLER_HPP_
